#!/usr/bin/env sh
#
BASEDIR=$(dirname "$0")
IAM_USER_KEY=$1

if [ -z "${IAM_USER_KEY}" ]
then
  echo "Please specify aws key"
  echo "Example: $0 ASHAUDI7OHTH0TASHI8O"
  exit 1
fi

if ! FOUND_RESULT=$(grep -ir "${IAM_USER_KEY}" "${BASEDIR}/profile_cache" 2>/dev/null)
then
  echo "IAM Key ${IAM_USER_KEY} not found"
  exit 1
fi
