#!/usr/bin/env sh
#

# We are cool guys ;-)
set -e

# Change this if you want to
BASEDIR=$(dirname $0)

if [ ! -f "${BASEDIR}/.profiles" ] && [ -z "${AWS_PROFILES}" ]
then
  echo "You need to create .profiles configuration file first or define environment variable AWS_PROFILES"
  exit 1
fi

[ -d "${BASEDIR}/profile_cache" ] || mkdir -p "${BASEDIR}/profile_cache"


if [ -z "${AWS_PROFILES}" ]
then
  . "${BASEDIR}/.profiles"
fi

echo "Building local cache of all IAM users from..."

for profile in ${AWS_PROFILES}
do

  USERS=$(aws --profile "${profile}" --output 'text' iam list-users | awk '{print $NF}')

  echo "- Profile: ${profile}"

  # Let's clean old data
  :> "${BASEDIR}/profile_cache/${profile}"

  for user in $USERS
  do
    #aws --profile "${profile}" --output 'text' iam list-access-keys --user-name "${user}" | tee -a file.txt
    aws --profile "${profile}" --output 'text' iam list-access-keys --user-name "${user}" >> "${BASEDIR}/profile_cache/${profile}"

    # ctrl+c support
    test $? -gt 128 && exit
  done

done

echo "done"
